name: Deploy to EC2

on:
  push:
    branches:
      - main  # o master o develop...

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user  # o ubuntu, a seconda dell'AMI
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/skills-react
            git pull origin main
            docker build -t skills-react .
            docker stop skills-react || true && docker rm skills-react || true
            docker run -d -p 80:80 skill-fe
